name: solutions_to_solveet_exercises
author: rchavarria
description: A set of solutions to [Solveet] exercises writen in the Dart programming language
homepage: http://rchavarria.github.io
dev_dependencies:
    unittest: '>=0.10.0'
    dartmocks: any

